version: '3.7'

services:
  app:
    container_name: docekr-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - 8080:80
    networks:
      - shared_backend

networks:
  shared_backend:
    external: true